version: '3.8'
services:
  node-server:
    image: node-graphql-img
    build: .
    container_name: mutatiton_node_server
    volumes:
      - .:/graphql_node/
      - node_modules:/graphql_node/node_modules 
    working_dir: /graphql_node/
    ports:
      - 4001:4000
volumes:
  node_modules: {}